--SUBSTRING
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA DUNYA'
SELECT SUBSTRING(@KELIME,9,5)

--LOWER,UPPER
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='Merhaba Dünya'
SELECT LOWER(@KELIME), UPPER(@KELIME)

--STRÝNG BÝRLEÞTÝRME
DECLARE @AD AS VARCHAR(100)='ÖMER'
DECLARE @SOYAD AS VARCHAR(100)='ÇOLAKOÐLU'
SELECT @AD+' '+@SOYAD

--RIGHT,LEFT
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='Merhaba Dünya'
SELECT LEFT(@KELIME,7),RIGHT(@KELIME,5)

--LTRIM,RTRIM,TRIM
DECLARE @KELIME AS VARCHAR(100)=' MERHABA DÜNYA '
SELECT LTRIM(@KELIME),RTRIM(@KELIME),TRIM(@KELIME)

--REPLACE
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT REPLACE(@KELIME,'Ü','U')
--SELECT REPLACE(@KELIME,'MERHABA','HELLO')
--SELECT REPLACE(REPLACE(@KELIME,'MERHABA','HELLO'),'DÜNYA','WORLD')


--LEN
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT LEN(@KELIME)


--STRING SPLIT
DECLARE @KELIME AS VARCHAR(100)='MERHABA DÜNYA'
SELECT *FROM string_split(@KELIME,' ')
