CREATE DATABASE TEST --OLUSTURUYORUZ
DROP DATABASE TEST --SILIYORUZ

CREATE TABLE ISIMLER(ID INT IDENTITY(1,1),ISIM VARCHAR(20))
INSERT INTO ISIMLER(ISIM) VALUES('ÖMER')
SELECT *FROM ISIMLER
DROP TABLE ISIMLER --TABLO ISMINI SÝLME

--MEVCUT BÝR TABLONUN ICINE YENÝ OZELLIK EKLEME
--1
DROP TABLE ISIMLER
CREATE TABLE ISIMLER(ID INT IDENTITY(1,1),ISIM VARCHAR(20), TELEFON VARCHAR(12))
--2
ALTER TABLE ISIMLER ADD TELEFON VARCHAR(12)
ALTER TABLE ISIMLER ADD ADRES VARCHAR(500)

--OLUÞTURULAN KOLONU SILME
ALTER TABLE ISIMLER DROP COLUMN ADRES