SELECT *FROM WORKERS WHERE WORKERBARCODE='B2485EFE-1393-440C-A16A-A885CC6AF3E5'

--1
ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)

	IF EXISTS(SELECT *FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE)
	BEGIN
		SELECT 'KART DOÐRU'
	END
	ELSE
	BEGIN
		SELECT 'KART YANLIÞ'
	END
END

--2
ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)
	SELECT @WORKERNAME=WORKERNAME FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE
	IF @WORKERNAME IS NULL
	BEGIN
		--SELECT 'KART BULUNAMADI'
		RAISERROR('KART BULUNAMADI',16,1)
		RETURN
	END
	ELSE
	BEGIN
		SELECT @WORKERNAME 
	END
END

EXEC SP_CARD_CONTROL 'A2485EFE-1393-440C-A16A-A885CC6AF3E5'
