CREATE FUNCTION DBO.GET_ITEM_INFO(@ITEMID INT)
RETURNS TABLE
AS
RETURN
(
SELECT 
	MIN(UNITPRICE) AS MINPRICE,
	MAX(UNITPRICE) AS MAXPRICE,
	AVG(UNITPRICE) AS AVGPRICE,
	SUM(LINETOTAL) AS TOTALSALE,
	SUM(AMOUNT) AS TOTALAMOUNT
FROM ORDERDETAILS WHERE ITEMID=@ITEMID
)


SELECT *FROM DBO.GET_ITEM_INFO(3)

--ÜRÜN ANALÝZÝ
SET STATISTICS TIME ON
SELECT ITM.ID,ITM.ITEMCODE MALZEMEKODU,ITM.ITEMNAME MALZEMEADI,
	ITEMINFO.MINPRICE AS ENDUSUKFIYAT,
	ITEMINFO.MAXPRICE AS ENYUKSEKFIYAT,
	ITEMINFO.AVGPRICE AS ORTALAMAFIYAT,
	ITEMINFO.TOTALSALE AS TOPLAMSATISTUTAR,
	ITEMINFO.TOTALAMOUNT AS TOPLAMSATISMIKTARI
FROM ITEMS ITM
CROSS APPLY DBO.GET_ITEM_INFO(ITM.ID) AS ITEMINFO