--1
CREATE FUNCTION DBO.TOPLA(@SAYI1 AS INT,@SAYI2 AS INT)
RETURNS INT
AS
BEGIN
	DECLARE @SONUC AS INT
	SET @SONUC=@SAYI1+@SAYI2
	RETURN @SONUC
END

SELECT DBO.TOPLA(13,39)


--2
CREATE FUNCTION DBO.CALCULATE_AGE(@BIRTHDATE AS DATE)
RETURNS INT
AS
BEGIN

DECLARE @RESULT AS INT
SET @RESULT=DATEDIFF(YEAR,@BIRTHDATE,GETDATE())

RETURN @RESULT
END

SELECT DBO.CALCULATE_AGE('19900101')

--3
SELECT TOP 1000*,
DBO.CALCULATE_AGE(BIRTHDATE) AS AGE
FROM CUSTOMERS