SELECT
ITM.ITEMCODE MALZEMEKODU,ITM.ITEMNAME MALZEMEADI,MIN(OD.UNITPRICE) AS ENDUSUKFIYAT,
MAX(OD.UNITPRICE) AS ENYUKSEKFIYAT,AVG(OD.UNITPRICE) AS ORTALAMAFIYAT,
SUM(OD.LINETOTAL) AS TOPLAMSATISTUTAR,SUM(OD.AMOUNT) AS TOPLAMSATISMIKTAR

FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

GROUP BY ITM.ITEMCODE,ITM.ITEMNAME

--ÜRÜN ANALÝZÝ
SELECT ITM.ID,ITM.ITEMCODE MALZEMEKODU,ITM.ITEMNAME MALZEMEADI,
--(SELECT MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=ITM.ID) AS ENDUSUKFIYAT,
--(SELECT MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=ITM.ID) AS ENYUKSEKFIYAT
DBO.GET_ITEM_MINPRICE(ITM.ID) AS ENDUSUKFIYAT,
DBO.GET_ITEM_MAXPRICE(ITM.ID) AS ENYUKSEKFIYAT
FROM ITEMS ITM

--FUNCTION
CREATE FUNCTION DBO.GET_ITEM_MINPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE @RESULT AS FLOAT
	SELECT @RESULT=MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID
	RETURN @RESULT
END

UPDATE STATISTICS ORDERDETAILS

SELECT DBO.GET_ITEM_MINPRICE(84)