ALTER VIEW VW_SIPARIS_DETAYLI
AS

SELECT TOP 1000
U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,U.TELNR1,U.TELNR2,
ITM.CATEGORY1 KATEGORI1,ITM.CATEGORY2 KATEGORI2,ITM.CATEGORY3 KATEGORI3,ITM.CATEGORY4 KATEGORI4,
C.COUNTRY ULKE,CT.CITY SEHIR,T.TOWN ILCE,
A.ADDRESSTEXT ACIKADRES,
O.ID SIPARISID,
ITM.ITEMCODE URUNKODU,ITM.ITEMNAME URUNADI,ITM.BRAND MARKA,
OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI,
CONVERT(DATE,O.DATE_) AS SIPARISTARIHI, CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) AS YIL,
CASE
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ÞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZÝRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AÐUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKÝM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
END AS AY,
CASE
	WHEN DATEPART(DW,O.DATE_)=2 THEN 'PAZARTESÝ'
	WHEN DATEPART(DW,O.DATE_)=3 THEN 'SALI'
	WHEN DATEPART(DW,O.DATE_)=4 THEN 'ÇARÞAMBA'
	WHEN DATEPART(DW,O.DATE_)=5 THEN 'PERÞEMBE'
	WHEN DATEPART(DW,O.DATE_)=6 THEN 'CUMA'
	WHEN DATEPART(DW,O.DATE_)=7 THEN 'CUMARTESÝ'
	WHEN DATEPART(DW,O.DATE_)=1 THEN 'PAZAR'
END AS HAFTANINGUNU
FROM
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID

SELECT *FROM VW_SIPARIS_DETAYLI

CREATE VIEW VW_TOP10_KATEGORI
AS

SELECT TOP 10
KATEGORI1,SUM(SATIRTOPLAMI) AS TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI
GROUP BY KATEGORI1
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT * FROM VW_TOP10_KATEGORI

CREATE VIEW VW_MAGAZA_ANALIZI
AS
SELECT SEHIR,SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI
GROUP BY SEHIR

SELECT *FROM VW_MAGAZA_ANALIZI



CREATE VIEW VW_TOP1000_MUSTERI_LISTESI
AS
SELECT
TOP 1000
KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELNR1,TELNR2,SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI
GROUP BY KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELNR1,TELNR2
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT *FROM VW_TOP1000_MUSTERI_LISTESI